### PR TITLE
Changes with all the files and features of TO-Do-List

### PR DESCRIPTION
**Pull request by TadesseDev**
##Main changes introduced
---
- Import all the files from the main repository
- All features are included in the new pull request.
- main branch is totaly empity.

### CODE REVIEW

**Comment by fed1k** [comment]
# Good points
 * Used ES6 modules 👍
 * Used Descriptive names for variables 👍
 * Used comments for Readibility 👍
 * Used different ES6 arrow functions instead of putting them in one function 👍
 * The code is very organized and clean 👍
# Suggestions
  * For edit input part, kindly adding enter event would be great so that when the user edits the list and can click enter button.
  * Fixing the eslint issue would be great but that is optional ( 👍 )

**Review by fed1k — APPROVED** [review]

**Review by fed1k — APPROVED** [review]
# STATUS: 🟢APPROVED
Your project is complete! There is nothing else to say other than... it's time to merge it 👍 👍 😄 👏

Congratulations! 🎉 🎉 🎉

you-rock-it-you-kill-it
## Highlights
*  👍 Used ES6 modules
* 👍 Used Descriptive names for variables 
* 👍  Used comments for Readibility 
*  👍 Used different ES6 arrow functions instead of putting them in one function 
* 👍 The code is very organized and clean 

# OPTIONAL Changes
* For edit input part, kindly adding enter event would be great so that when the user edits the list and can click enter button.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by TadesseDev** [comment]
@fed1k Thank you! 🙏🏼I'll make the changes before merging the branch.

**Comment by TadesseDev** [comment]
@fed1k Thaks for the review, as you can see I have made the requested changes. Please do let me know if anything I should improve.

**Comment by fed1k** [comment]
@Tadesse-Alemayehu Everything is perfect. Keep up the good work

**Pull request merged**
